// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.17.3
// source: api/proto/fm_flats.proto

package flats_manager_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FlatsService_CreateFlat_FullMethodName = "/FlatsService/CreateFlat"
)

// FlatsServiceClient is the client API for FlatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlatsServiceClient interface {
	CreateFlat(ctx context.Context, in *CreateFlatRequest, opts ...grpc.CallOption) (*Flat, error)
}

type flatsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlatsServiceClient(cc grpc.ClientConnInterface) FlatsServiceClient {
	return &flatsServiceClient{cc}
}

func (c *flatsServiceClient) CreateFlat(ctx context.Context, in *CreateFlatRequest, opts ...grpc.CallOption) (*Flat, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Flat)
	err := c.cc.Invoke(ctx, FlatsService_CreateFlat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlatsServiceServer is the server API for FlatsService service.
// All implementations must embed UnimplementedFlatsServiceServer
// for forward compatibility.
type FlatsServiceServer interface {
	CreateFlat(context.Context, *CreateFlatRequest) (*Flat, error)
	mustEmbedUnimplementedFlatsServiceServer()
}

// UnimplementedFlatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlatsServiceServer struct{}

func (UnimplementedFlatsServiceServer) CreateFlat(context.Context, *CreateFlatRequest) (*Flat, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFlat not implemented")
}
func (UnimplementedFlatsServiceServer) mustEmbedUnimplementedFlatsServiceServer() {}
func (UnimplementedFlatsServiceServer) testEmbeddedByValue()                      {}

// UnsafeFlatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlatsServiceServer will
// result in compilation errors.
type UnsafeFlatsServiceServer interface {
	mustEmbedUnimplementedFlatsServiceServer()
}

func RegisterFlatsServiceServer(s grpc.ServiceRegistrar, srv FlatsServiceServer) {
	// If the following call pancis, it indicates UnimplementedFlatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FlatsService_ServiceDesc, srv)
}

func _FlatsService_CreateFlat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFlatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlatsServiceServer).CreateFlat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlatsService_CreateFlat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlatsServiceServer).CreateFlat(ctx, req.(*CreateFlatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FlatsService_ServiceDesc is the grpc.ServiceDesc for FlatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FlatsService",
	HandlerType: (*FlatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFlat",
			Handler:    _FlatsService_CreateFlat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/fm_flats.proto",
}
